<!DOCTYPE HTML>

<html>
	<head>
		<title>HISTOIRES</title>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="stylesheet.css" />
		<link rel="stylesheet"href= "polices/polices.css"></link>
	</head>
	
	<body>
		<header>
			<div class= "inside">
			
			</div>
		</header>
		
		<main>
			<div class= "inside">
				<?php include $template ?>
			</div>
		</main>
		
		<footer>
			<div class= "inside">
			</div>
		</footer>
		
	</body>
</html>